
package fr.ibty.agenceWebService.hotel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHotelService", targetNamespace = "http://hotelWebService.ibty.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHotelService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserver", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.Reserver")
    @ResponseWrapper(localName = "reserverResponse", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.ReserverResponse")
    @Action(input = "http://hotelWebService.ibty.fr/IHotelService/reserverRequest", output = "http://hotelWebService.ibty.fr/IHotelService/reserverResponse")
    public String reserver(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNom", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.GetNom")
    @ResponseWrapper(localName = "getNomResponse", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.GetNomResponse")
    @Action(input = "http://hotelWebService.ibty.fr/IHotelService/getNomRequest", output = "http://hotelWebService.ibty.fr/IHotelService/getNomResponse")
    public String getNom();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReduction", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.GetReduction")
    @ResponseWrapper(localName = "getReductionResponse", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.GetReductionResponse")
    @Action(input = "http://hotelWebService.ibty.fr/IHotelService/getReductionRequest", output = "http://hotelWebService.ibty.fr/IHotelService/getReductionResponse")
    public Integer getReduction(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

   
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercher", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.Rechercher")
    @ResponseWrapper(localName = "rechercherResponse", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.RechercherResponse")
    @Action(input = "http://hotelWebService.ibty.fr/IHotelService/rechercherRequest", output = "http://hotelWebService.ibty.fr/IHotelService/rechercherResponse")
    public List<String> rechercher(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddresse", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.GetAddresse")
    @ResponseWrapper(localName = "getAddresseResponse", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.GetAddresseResponse")
    @Action(input = "http://hotelWebService.ibty.fr/IHotelService/getAddresseRequest", output = "http://hotelWebService.ibty.fr/IHotelService/getAddresseResponse")
    public String getAddresse();

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtoiles", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.GetEtoiles")
    @ResponseWrapper(localName = "getEtoilesResponse", targetNamespace = "http://hotelWebService.ibty.fr/", className = "fr.ibty.agenceWebService.hotel.GetEtoilesResponse")
    @Action(input = "http://hotelWebService.ibty.fr/IHotelService/getEtoilesRequest", output = "http://hotelWebService.ibty.fr/IHotelService/getEtoilesResponse")
    public Integer getEtoiles();

}
